################################################################################################################
#    _  __          _                      _              _                       _     _   _                  #
#   | |/ /   __ _  | |_   ___   _   _     / \     _ __   (_)  _ __ ___     __ _  | |_  (_)   ___    _ __       #
#   | ' /   / _` | | __| / __| | | | |   / _ \   | '_ \  | | | '_ ` _ \   / _` | | __| | |  / _ \  | '_ \      #
#   | . \  | (_| | | |_  \__ \ | |_| |  / ___ \  | | | | | | | | | | | | | (_| | | |_  | | | (_) | | | | |     #
#   |_|\_\  \__,_|  \__| |___/  \__,_| /_/   \_\ |_| |_| |_| |_| |_| |_|  \__,_|  \__| |_|  \___/  |_| |_|     #
#                                                                                                              #
################################################################################################################
#-                                    *\ Created by Katsutori Studio © /*                                     -#
################################################################################################################

config:

  # Finish the animation when the player quit the server.
  finish-animation-on-quit: true

  # This enables the texture pack self host in the plugin
  # for use this you need open the port in the server firewall
  # or ask your host for an additional port, most of the time you can add it from your host panel.
  texture-pack-host:
    enabled: true
    port: 8080

    # If your host is used a https connection you need to enable this option
    SSL: false

  # This option is for the texture pack join, if you want to use the texture pack join
  # you need to enable this option and put the url of the texture pack host
  texture-pack-join:
    enable: true

    # The url of the texture pack host if you use "self-host", the plugin will use the self hosting
    # you can use external host like https://mc-packs.net/ or https://www.dropbox.com/
    url: "self-host"


# All the messages of the plugin
# You can use the color codes with the symbol "&"
messages:
  compile: "&aSuccess compile the texture pack saved in plugins/KatsuAnimation/resoucepack.zip"
  no-args: "&cPlease complete command, use /kta for see available commands."
  no-args-create: "&cPlease complete command, use /kta create <gif/url> <skip-frames> <size> <height>"
  no-args-delete: "&cPlease complete command, use /kta delete <gif>"
  no-args-animation: "&cPlease complete command, use /kta animation <play/stop> "
  no-args-animation-stop: "&cPlease complete command, use /kta animation stop <player>"
  no-args-animation-play: "&cPlease complete command, use /kta animation play <gif> <repeat> <tick-update> <player>"
  no-active-animation: "&cThe player does not have an active animation."
  no-args-apply: "&cPlease complete command, use /kta apply <player>"
  no-permission: "&cYou do not have permission to use this command."
  gif-not-found: "&cGif not found, make sure the gif is in the plugins/KatsuParkour/gifs folder."
  gif-not-exist: "&cNo exist any gif with this name."
  gif-exist: "&cThe gif with this name already exist, if you want to delete use /kta delete <gif>."
  boolean-error: "&cPlease use true or false in repeat mode example /kta animation animation play <gif> true <tick-update> <player>"
  animation-type-error: "&cPlease use correct type TITLE, ACTION_BAR"
  player-not-found: "&cPlayer not found, make sure the player is online."
  active-animation: "&cThe player already has an active animation."
  play-animation: "&aSuccess play the animation &e%animation% &ato the player.."
  play-animation-all: "&aSuccess play the animation &e%animation% &ato the all players.."
  stop-animation: "&aSuccess stop the animation to the player."
  stop-animation-all: "&aSuccess stop the animation to the all players."
  apply-texture-all: "&aSuccess apply the texture to the all players."
  apply-texture: "&aSuccess apply the texture to the %player%."
  download-error: "&cError download the gif, make sure the gif is a valid url."
  download-gif: "&aSuccess download the gif with name &e%name%&a, use /kta create to create the texture pack."
  delete-texture: "&aSuccess delete the texture, use /kta compile to compile again the texture pack."
  create-texture: "&aSuccess create the texture, use /kta compile to compile the texture pack."
  texture-host-not-started: "&cThe texture pack host is not started, see the console for more information."
  reload: "&aReloaded the config file."