name: KatsuAnimation
version: '${project.version}'
main: io.github.maazapan.katsuAnimation.KatsuAnimation
api-version: 1.16
softdepend:
  - ProtocolLib

commands:
  kta:
    aliases:
      - katsuanimation
